### ISSUE TITLE
Окно кода

### ISSUE THREAD

**Issue by bramind** [RTUITLab/Olympiad#2]
После отправки решения на проверку сверху окна кода остается статус прошлого решения, что смущает пользователя который уже загрузил новый код.

**Comment by CAPCHIK** [comment]
Приложи скрины видео, не совсем ясна проблема.

**Comment by CAPCHIK** [comment]
Недопонимание в способе работы системы, будет решено в RTUITLab/Olympiad-Front/issues/31
